spring:
 application:
   name: simple-java-client
#  cloud:
#    inetutils:
#      ignoredInterfaces:
#        - en.*
#eureka:
#  instance:
#    nonSecurePort: 13456
#    preferIpAddress: true
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#  client:
#    enabled: true
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:18888/eureka/eureka/
#      #defaultZone: http://localhost:18888/eureka/eureka/
eureka:
  client:
    defaultZone: http://localhost:18888/public/eureka/
  instance:
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}}
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}}
      pub: 'true'
  maxRetries: 40

server:
  port: 8761